### ISSUE TITLE
Cannot upgrade react native to 0.71 and up Gradle plugin version 1.6.20 and higher

### ISSUE THREAD

**Issue by sam-houle1** [Ziggeo/ReactNativeSDK#112] opened 2023-08-30 18:40 UTC
<img width="1100" alt="Screenshot 2023-08-30 at 2 39 54 PM" src="https://github.com/Ziggeo/ReactNativeSDK/assets/44783494/f8a5972e-82c9-4b2a-9d08-0202e0856961">

**Comment by sam-houle1** [comment] 2023-08-30 18:42
Hey @katolykdev, not sure if you still work on this project, but this is a critical issue, we can't upgrade our react native version to 0.71 and up, and if we don't we won't be able to release any versions on the android play store after August 31st.

**Comment by Bane-D** [comment] 2023-08-31 21:48
Hi Sam,

Since the 31st is here already it would be best to ask for extension. You can do this through the Google Play Console for each app that has this requirement and you would get additional 30 days.

In the meantime this is assigned to one of our colleagues to look into and follow up with you.

**Comment by sam-houle1** [comment] 2023-10-16 21:31
Hi @Bane-D, the 30 additional days are over for more than a month now. We've disabled the feature that use this package because we were stuck on release. 

Do you have a status on this ?

**Comment by Bane-D** [comment] 2023-10-17 17:11
Hi Sam, this should have been fixed already. Are you still having issues with the latest version of our SDK? Also do let me know if you are using any of our non-master branches.

**Comment by 3akat** [comment] 2023-10-20 13:02
Hi @sam-houle1, Please take a look at the version 1.6.35. It's working with react-native: 0.72.6

**Comment by sam-houle1** [comment] 2023-10-24 21:45
Hi @3akat @Bane-D, I'm currently on 0.71.13, and it's not working for android, ios and simulators. Do I have to upgrade to 0.72.6 to use the latest version of the package ?

**Comment by 3akat** [comment] 2023-10-27 08:19
Hi @sam-houle1, I just tried creating an empty project with react version 0.71.13 and ziggeo version 1.6.35 and everything works well for android. What error do you have now? This is package.json that I have 
<img width="522" alt="Screenshot 2023-10-27 at 11 17 39" src="https://github.com/Ziggeo/ReactNativeSDK/assets/2178533/3a663496-7187-4776-9a03-fad7bf6b3ff3">

**Comment by sam-houle1** [comment] 2023-11-13 22:01
@3akat hi, sorry for the late response.

on Android:
![Screenshot 2023-11-13 at 4 57 02 PM](https://github.com/Ziggeo/ReactNativeSDK/assets/44783494/77e7dcdd-b720-4aaa-988f-596d991e4297)

Ios Simulator:
![Screenshot 2023-11-13 at 4 59 29 PM](https://github.com/Ziggeo/ReactNativeSDK/assets/44783494/53a3e0a0-951c-416e-bf38-8d0c62f7e278)


Let me know if you need any other information.

**Comment by sam-houle1** [comment] 2023-11-27 18:45
@3akat hi can we still work on this issue ? We still can't use ziggeo in our app. What information I need to send you?

**Comment by jdeslauriers** [comment] 2023-12-05 16:26
Hi @3akat and @Bane-D ! 

Can we have more assistance on this ? It seems the problem is still there, and it has become critical for our applications because we had to remove completely the feature to compile the application.

We've been a customer for 2 years now, but these packages issue are becoming a problem for us.

**Comment by Bane-D** [comment] 2023-12-05 21:58
Hi Jocelyn, I know my colleague was doing different tests and was not able to recreate it, so just to help him and you to speed things along:
1. Have you tried in a fresh project just to confirm that it is working or not working for you there?
2. Do you experience the same issue with React Native 0.71.13 and Ziggeo 1.6.35?
3. Do you experience the same issue with React Native 0.72.6 and Ziggeo 1.6.35?

**Comment by 3akat** [comment] 2023-12-06 09:54
Hi, can you show your android/build.gradle file? You needed to add  jcenter() repository in it for correct working of exoplayer implementation. Also all ios issues must be fixed in 1.6.36.
<img width="692" alt="Screenshot 2023-12-06 at 10 46 58" src="https://github.com/Ziggeo/ReactNativeSDK/assets/2178533/1b16dd28-7db1-4ab5-8413-002a9656a816">

**Comment by 3akat** [comment] 2024-01-15 08:12
@sam-houle1 , @jdeslauriers Do you have any updates on this issue?

**Comment by sam-houle1** [comment] 2024-01-15 17:22
Hi @3akat, I've opened a new [issue](https://github.com/Ziggeo/ReactNativeSDK/issues/113) to ask if it's possible to use the api and let us handle the camera with our own package, we want to use a single component that handles the camera.

**Closed as completed** 2024-05-30 19:59 UTC
